export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
